default: all

HOST=$(shell hostname)

all:
	autopoint
	libtoolize --force --copy
	aclocal -I m4
	autoheader
	automake --add-missing
	autoconf
	./configure
	rm -rf html.internal
	doxygen
	tar cfz libpst.html.tar.gz html.internal
